const lightColors = {
  root: {
    primary: {
      background: '{primary.color}',
      hoverBackground: '{primary.hover}',
      activeBackground: '{primary.active}',
      borderColor: '{primary.color}',
      hoverBorderColor: '{primary.color}',
      activeBorderColor: '{primary.color}',
      color: '{primary.foreground}',
      hoverColor: '{primary.foreground}',
      activeColor: '{primary.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    secondary: {
      background: '{secondary.color}',
      hoverBackground: '{secondary.hover}',
      activeBackground: '{secondary.active}',
      borderColor: '{secondary.color}',
      hoverBorderColor: '{secondary.color}',
      activeBorderColor: '{secondary.color}',
      color: '{secondary.foreground}',
      hoverColor: '{secondary.foreground}',
      activeColor: '{secondary.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    success: {
      background: '{success.color}',
      hoverBackground: '{success.hover}',
      activeBackground: '{success.active}',
      borderColor: '{success.color}',
      hoverBorderColor: '{success.color}',
      activeBorderColor: '{success.color}',
      color: '{success.foreground}',
      hoverColor: '{success.foreground}',
      activeColor: '{success.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    warn: {
      background: '{warn.color}',
      hoverBackground: '{warn.hover}',
      activeBackground: '{warn.active}',
      borderColor: '{warn.color}',
      hoverBorderColor: '{warn.color}',
      activeBorderColor: '{warn.color}',
      color: '{warn.foreground}',
      hoverColor: '{warn.foreground}',
      activeColor: '{warn.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    error: {
      background: '{error.color}',
      hoverBackground: '{error.hover}',
      activeBackground: '{error.active}',
      borderColor: '{error.color}',
      hoverBorderColor: '{error.color}',
      activeBorderColor: '{error.color}',
      color: '{error.foreground}',
      hoverColor: '{error.foreground}',
      activeColor: '{error.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    info: {
      background: '{info.color}',
      hoverBackground: '{info.hover}',
      activeBackground: '{info.active}',
      borderColor: '{info.color}',
      hoverBorderColor: '{info.color}',
      activeBorderColor: '{info.color}',
      color: '{info.foreground}',
      hoverColor: '{info.foreground}',
      activeColor: '{info.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    /**
     * TODO @Oleksandr Palonnyi
     * need to replace name "job" to "task",
     * */
    job: {
      background: '{task.color}',
      hoverBackground: '{task.hover}',
      activeBackground: '{task.active}',
      borderColor: '{task.color}',
      hoverBorderColor: '{task.color}',
      activeBorderColor: '{task.color}',
      color: '{task.foreground}',
      hoverColor: '{task.foreground}',
      activeColor: '{task.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    transfer: {
      background: '{transfer.color}',
      hoverBackground: '{transfer.hover}',
      activeBackground: '{transfer.active}',
      borderColor: '{transfer.color}',
      hoverBorderColor: '{transfer.color}',
      activeBorderColor: '{transfer.color}',
      color: '{transfer.foreground}',
      hoverColor: '{transfer.foreground}',
      activeColor: '{transfer.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    disabled: {
      color: '{gray.600}',
      background: '{gray.200}',
    },
  },
  outlined: {
    primary: {
      hoverBackground: '{primary.50}',
      activeBackground: '{primary.100}',
      borderColor: '{primary.color}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.600}',
      color: '{surface.600}',
    },
    success: {
      hoverBackground: '{green.50}',
      activeBackground: '{green.100}',
      borderColor: '{green.500}',
      color: '{green.500}',
    },
    info: {
      hoverBackground: '{sky.50}',
      activeBackground: '{sky.100}',
      borderColor: '{sky.500}',
      color: '{sky.500}',
    },
    warn: {
      hoverBackground: '{orange.50}',
      activeBackground: '{orange.100}',
      borderColor: '{orange.500}',
      color: '{orange.500}',
    },
    help: {
      hoverBackground: '{purple.50}',
      activeBackground: '{purple.100}',
      borderColor: '{purple.500}',
      color: '{purple.500}',
    },
    danger: {
      hoverBackground: '{red.50}',
      activeBackground: '{red.100}',
      borderColor: '{red.500}',
      color: '{red.500}',
    },
    contrast: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.950}',
      color: '{surface.950}',
    },
    plain: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.900}',
      color: '{surface.900}',
    },
  },
  text: {
    primary: {
      hoverBackground: '{primary.50}',
      activeBackground: '{primary.100}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.600}',
    },
    success: {
      hoverBackground: '{green.50}',
      activeBackground: '{green.100}',
      color: '{green.500}',
    },
    info: {
      hoverBackground: '{sky.50}',
      activeBackground: '{sky.100}',
      color: '{sky.500}',
    },
    warn: {
      hoverBackground: '{orange.50}',
      activeBackground: '{orange.100}',
      color: '{orange.500}',
    },
    help: {
      hoverBackground: '{purple.50}',
      activeBackground: '{purple.100}',
      color: '{purple.500}',
    },
    danger: {
      hoverBackground: '{red.50}',
      activeBackground: '{red.100}',
      color: '{red.500}',
    },
    contrast: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.950}',
    },
    plain: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.900}',
    },
  },
  link: {
    color: '{primary.color}',
    hoverColor: '{primary.color}',
    activeColor: '{primary.color}',
  },
};

export default lightColors;
