const lightColors = {
  root: {
    primary: {
      background: '{primary-color}',
      hoverBackground: '{primary-hover-color}',
      activeBackground: '{primary-active-color}',
      borderColor: '{primary-color}',
      hoverBorderColor: '{primary-hover-color}',
      activeBorderColor: '{primary-active-color}',
      color: '{primary-on-color}',
      hoverColor: '{primary-on-color}',
      activeColor: '{primary-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    secondary: {
      background: '{secondary-color}',
      hoverBackground: '{secondary-hover-color}',
      activeBackground: '{secondary-active-color}',
      borderColor: '{secondary-color}',
      hoverBorderColor: '{secondary-hover-color}',
      activeBorderColor: '{secondary-active-color}',
      color: '{secondary-on-color}',
      hoverColor: '{secondary-on-color}',
      activeColor: '{secondary-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    success: {
      background: '{success-color}',
      hoverBackground: '{success-hover-color}',
      activeBackground: '{success-active-color}',
      borderColor: '{success-color}',
      hoverBorderColor: '{success-hover-color}',
      activeBorderColor: '{success-active-color}',
      color: '{success-on-color}',
      hoverColor: '{success-on-color}',
      activeColor: '{success-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    warn: {
      background: '{warning-color}',
      hoverBackground: '{warning-hover-color}',
      activeBackground: '{warning-active-color}',
      borderColor: '{warning-color}',
      hoverBorderColor: '{warning-hover-color}',
      activeBorderColor: '{warning-active-color}',
      color: '{warning-on-color}',
      hoverColor: '{warning-on-color}',
      activeColor: '{warning-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    error: {
      background: '{error-color}',
      hoverBackground: '{error-hover-color}',
      activeBackground: '{error-active-color}',
      borderColor: '{error-color}',
      hoverBorderColor: '{error-hover-color}',
      activeBorderColor: '{error-active-color}',
      color: '{error-on-color}',
      hoverColor: '{error-on-color}',
      activeColor: '{error-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    info: {
      background: '{info-color}',
      hoverBackground: '{info-hover-color}',
      activeBackground: '{info-active-color}',
      borderColor: '{info-color}',
      hoverBorderColor: '{info-hover-color}',
      activeBorderColor: '{info-active-color}',
      color: '{info-on-color}',
      hoverColor: '{info-on-color}',
      activeColor: '{info-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    /**
     * TODO @Oleksandr Palonnyi
     * need to replace name "job" to "task",
     * */
    job: {
      background: '{task-color}',
      hoverBackground: '{task-hover-color}',
      activeBackground: '{task-active-color}',
      borderColor: '{task-color}',
      hoverBorderColor: '{task-hover-color}',
      activeBorderColor: '{task-active-color}',
      color: '{task-on-color}',
      hoverColor: '{task-on-color}',
      activeColor: '{task-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    transfer: {
      background: '{transfer-color}',
      hoverBackground: '{transfer-hover-color}',
      activeBackground: '{transfer-active-color}',
      borderColor: '{transfer-color}',
      hoverBorderColor: '{transfer-hover-color}',
      activeBorderColor: '{transfer-active-color}',
      color: '{transfer-on-color}',
      hoverColor: '{transfer-on-color}',
      activeColor: '{transfer-on-color}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    disabled: {
      color: '{grey-darken-1}',
      background: '{dp-surface-color-16}',
    },
  },
  outlined: {
    primary: {
      hoverBackground: '{primary.50}',
      activeBackground: '{primary.100}',
      borderColor: '{primary.color}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.600}',
      color: '{surface.600}',
    },
    success: {
      hoverBackground: '{green.50}',
      activeBackground: '{green.100}',
      borderColor: '{green.500}',
      color: '{green.500}',
    },
    info: {
      hoverBackground: '{sky.50}',
      activeBackground: '{sky.100}',
      borderColor: '{sky.500}',
      color: '{sky.500}',
    },
    warn: {
      hoverBackground: '{orange.50}',
      activeBackground: '{orange.100}',
      borderColor: '{orange.500}',
      color: '{orange.500}',
    },
    help: {
      hoverBackground: '{purple.50}',
      activeBackground: '{purple.100}',
      borderColor: '{purple.500}',
      color: '{purple.500}',
    },
    danger: {
      hoverBackground: '{red.50}',
      activeBackground: '{red.100}',
      borderColor: '{red.500}',
      color: '{red.500}',
    },
    contrast: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.950}',
      color: '{surface.950}',
    },
    plain: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.900}',
      color: '{surface.900}',
    },
  },
  text: {
    primary: {
      hoverBackground: '{primary.50}',
      activeBackground: '{primary.100}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.600}',
    },
    success: {
      hoverBackground: '{green.50}',
      activeBackground: '{green.100}',
      color: '{green.500}',
    },
    info: {
      hoverBackground: '{sky.50}',
      activeBackground: '{sky.100}',
      color: '{sky.500}',
    },
    warn: {
      hoverBackground: '{orange.50}',
      activeBackground: '{orange.100}',
      color: '{orange.500}',
    },
    help: {
      hoverBackground: '{purple.50}',
      activeBackground: '{purple.100}',
      color: '{purple.500}',
    },
    danger: {
      hoverBackground: '{red.50}',
      activeBackground: '{red.100}',
      color: '{red.500}',
    },
    contrast: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.950}',
    },
    plain: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.900}',
    },
  },
  link: {
    color: '{primary.color}',
    hoverColor: '{primary.color}',
    activeColor: '{primary.color}',
  },
};

export default lightColors;
