const lightColors = {
  root: {
    primary: {
      background: '{primary-color}',
      hoverBackground: '{primary.hover.color}',
      activeBackground: '{primary.active.color}',
      borderColor: '{primary.color}',
      hoverBorderColor: '{primary.hover.color}',
      activeBorderColor: '{primary.active.color}',
      color: '{primary.contrast.color}',
      hoverColor: '{primary.contrast.color}',
      activeColor: '{primary.contrast.color}',
      focusRing: {
        color: '{primary.color}',
        shadow: 'none',
      },
    },
    secondary: {
      background: '{surface.100}',
      hoverBackground: '{surface.200}',
      activeBackground: '{surface.300}',
      borderColor: '{surface.100}',
      hoverBorderColor: '{surface.200}',
      activeBorderColor: '{surface.300}',
      color: '{surface.600}',
      hoverColor: '{surface.700}',
      activeColor: '{surface.800}',
      focusRing: {
        color: '{surface.600}',
        shadow: 'none',
      },
    },
    info: {
      background: '{sky.500}',
      hoverBackground: '{sky.400}',
      activeBackground: '{sky.300}',
      borderColor: '{sky.500}',
      hoverBorderColor: '{sky.400}',
      activeBorderColor: '{sky.300}',
      color: '#ffffff',
      hoverColor: '#ffffff',
      activeColor: '#ffffff',
      focusRing: {
        color: '{sky.500}',
        shadow: 'none',
      },
    },
    success: {
      background: '{success-color}',
      hoverBackground: '{success-hover-color}',
      activeBackground: '{success-hover-color}',
      borderColor: '{green.500}',
      hoverBorderColor: '{green.400}',
      activeBorderColor: '{green.300}',
      color: '#ffffff',
      hoverColor: '#ffffff',
      activeColor: '#ffffff',
      focusRing: {
        color: '{green.500}',
        shadow: 'none',
      },
    },
    warn: {
      background: '{orange.500}',
      hoverBackground: '{orange.400}',
      activeBackground: '{orange.300}',
      borderColor: '{orange.500}',
      hoverBorderColor: '{orange.400}',
      activeBorderColor: '{orange.300}',
      color: '#ffffff',
      hoverColor: '#ffffff',
      activeColor: '#ffffff',
      focusRing: {
        color: '{orange.500}',
        shadow: 'none',
      },
    },
    help: {
      background: '{purple.500}',
      hoverBackground: '{purple.400}',
      activeBackground: '{purple.300}',
      borderColor: '{purple.500}',
      hoverBorderColor: '{purple.400}',
      activeBorderColor: '{purple.300}',
      color: '#ffffff',
      hoverColor: '#ffffff',
      activeColor: '#ffffff',
      focusRing: {
        color: '{purple.500}',
        shadow: 'none',
      },
    },
    danger: {
      background: '{red.500}',
      hoverBackground: '{red.400}',
      activeBackground: '{red.300}',
      borderColor: '{red.500}',
      hoverBorderColor: '{red.400}',
      activeBorderColor: '{red.300}',
      color: '#ffffff',
      hoverColor: '#ffffff',
      activeColor: '#ffffff',
      focusRing: {
        color: '{red.500}',
        shadow: 'none',
      },
    },
    contrast: {
      background: '{surface.950}',
      hoverBackground: '{surface.800}',
      activeBackground: '{surface.700}',
      borderColor: '{surface.950}',
      hoverBorderColor: '{surface.800}',
      activeBorderColor: '{surface.700}',
      color: '{surface.0}',
      hoverColor: '{surface.0}',
      activeColor: '{surface.0}',
      focusRing: {
        color: '{surface.950}',
        shadow: 'none',
      },
    },
    /**
     * TODO @Evgeniy Trahtenberg
     * need to refactor transfer, error and job colors
     * */
    transfer: {
      background: '{primary.color}',
      hoverBackground: '{primary.hover.color}',
      activeBackground: '{primary.active.color}',
      borderColor: '{primary.color}',
      hoverBorderColor: '{primary.hover.color}',
      activeBorderColor: '{primary.active.color}',
      color: '{primary.contrast.color}',
      hoverColor: '{primary.contrast.color}',
      activeColor: '{primary.contrast.color}',
      focusRing: {
        color: '{primary.color}',
        shadow: 'none',
      },
    },
    error: {
      background: '{error-color}',
      hoverBackground: '{error-hover-color}',
      activeBackground: '{error-hover-color}',
      borderColor: '{primary.color}',
      hoverBorderColor: '{primary.hover.color}',
      activeBorderColor: '{primary.active.color}',
      color: '{primary.contrast.color}',
      hoverColor: '{primary.contrast.color}',
      activeColor: '{primary.contrast.color}',
      focusRing: {
        color: '{primary.color}',
        shadow: 'none',
      },
    },
    job: {
      background: '{primary.color}',
      hoverBackground: '{primary.hover.color}',
      activeBackground: '{primary.active.color}',
      borderColor: '{primary.color}',
      hoverBorderColor: '{primary.hover.color}',
      activeBorderColor: '{primary.active.color}',
      color: '{primary.contrast.color}',
      hoverColor: '{primary.contrast.color}',
      activeColor: '{primary.contrast.color}',
      focusRing: {
        color: '{primary.color}',
        shadow: 'none',
      },
    },
    disabled: {
      color: '{grey.darken.1}',
      background: '{dp-surface-color.16}',
    },
  },
  outlined: {
    primary: {
      hoverBackground: '{primary.50}',
      activeBackground: '{primary.100}',
      borderColor: '{primary.color}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.600}',
      color: '{surface.600}',
    },
    success: {
      hoverBackground: '{green.50}',
      activeBackground: '{green.100}',
      borderColor: '{green.500}',
      color: '{green.500}',
    },
    info: {
      hoverBackground: '{sky.50}',
      activeBackground: '{sky.100}',
      borderColor: '{sky.500}',
      color: '{sky.500}',
    },
    warn: {
      hoverBackground: '{orange.50}',
      activeBackground: '{orange.100}',
      borderColor: '{orange.500}',
      color: '{orange.500}',
    },
    help: {
      hoverBackground: '{purple.50}',
      activeBackground: '{purple.100}',
      borderColor: '{purple.500}',
      color: '{purple.500}',
    },
    danger: {
      hoverBackground: '{red.50}',
      activeBackground: '{red.100}',
      borderColor: '{red.500}',
      color: '{red.500}',
    },
    contrast: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.950}',
      color: '{surface.950}',
    },
    plain: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      borderColor: '{surface.900}',
      color: '{surface.900}',
    },
  },
  text: {
    primary: {
      hoverBackground: '{primary.50}',
      activeBackground: '{primary.100}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.600}',
    },
    success: {
      hoverBackground: '{green.50}',
      activeBackground: '{green.100}',
      color: '{green.500}',
    },
    info: {
      hoverBackground: '{sky.50}',
      activeBackground: '{sky.100}',
      color: '{sky.500}',
    },
    warn: {
      hoverBackground: '{orange.50}',
      activeBackground: '{orange.100}',
      color: '{orange.500}',
    },
    help: {
      hoverBackground: '{purple.50}',
      activeBackground: '{purple.100}',
      color: '{purple.500}',
    },
    danger: {
      hoverBackground: '{red.50}',
      activeBackground: '{red.100}',
      color: '{red.500}',
    },
    contrast: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.950}',
    },
    plain: {
      hoverBackground: '{surface.50}',
      activeBackground: '{surface.100}',
      color: '{surface.900}',
    },
  },
  link: {
    color: '{primary.color}',
    hoverColor: '{primary.color}',
    activeColor: '{primary.color}',
  },
};

export default lightColors;
